---
- name: issue
  hosts: all
  tasks:
  
    - name: dev
      copy:
        content: "Development"
        dest: /etc/issue

    - name: test
      copy:
        content: "Test"
        dest: /etc/issue
    - name: prod
      copy:
        content: "Production"
        dest: /etc/issue
