---
- name: repo
  hosts: all
  tasks:
  
    - name: baseos
      yum_repository:
        name: "baseos"
        description: "BaseOS Description"
        baseurl: http://ec2-54-162-204-86.compute-1.amazonaws.com/BaseOs/
        enabled: true
        gpgcheck: true
        gpgkey: http://ec2-54-162-204-86.compute-1.amazonaws.com/RPM-GPG-KEY-redhat-release
    - name: Appstream
      yum_repository:
        name: "appstream"
        description: "App Description"
        baseurl: http://ec2-54-162-204-86.compute-1.amazonaws.com/AppStream/
        enabled: true
        gpgcheck: true
        gpgkey: http://ec2-54-162-204-86.compute-1.amazonaws.com/RPM-GPG-KEY-redhat-release
